name: list_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_riverpod:
  riverpod_annotation: 
  hooks_riverpod:
  flutter_hooks: 
  get: ^4.6.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  flutter_bloc:
  provider: ^6.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: 
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
